### ISSUE TITLE
<strong> 태그가 반영되지 않음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/plugin-alice#4]
게시판에서 굵게 사용시 입력되는 `<strong>` 태그가 강제 지정되어 있어 굵게 지정을 해도 똑같이 보입니다.
이는 `/plugins/alice/assets/css/materialize.css` 에서

``` css
strong {
  font-weight: 500; }
```

으로 초기화하여 발생하는 문제입니다.
